#!/bin/sh

GENERATE() {
  dst=$1
  src=$1.m4
  m4 -I examples $src > $dst
}

INSTALL() {
	src=$(pwd)/$1
	dst=~/$1
	dir=$(dirname $dst)
	rm -f $dst
	mkdir -p $dir
	ln -s $src $dst	
}

INSTALL ".vimrc"
INSTALL ".lesskey"
INSTALL ".zshrc"
INSTALL ".tmux.conf"
INSTALL ".config/i3/config"
INSTALL ".config/ranger/rc.conf"
INSTALL ".config/kitty/kitty.conf"

GENERATE ".config/i3status/config"
INSTALL ".config/i3status/config"
