#!/bin/sh

INSTALL() {
	src=$(pwd)/$1
	dst=~/$1
	dir=$(dirname $dst)
	rm -f $dst
	mkdir -p $dir
	ln -s $src $dst	
}

INSTALL ".vimrc"
INSTALL ".lesskey"
INSTALL ".config/i3/config"
INSTALL ".config/ranger/rc.conf"
