#!/bin/sh
ln -s .config/i3/config ~/.config/i3/config
ln -s .config/i3status/config ~/.config/i3status/config
ln -s .vimrc ~/.vimrc
ln -s .config/ranger/rc.conf ~/.config/ranger/rc.conf
ln -s .lesskey ~/.lesskey
